"use client";

import Link from "next/link";
import { useLanguage } from "@/lib/i18n";

export default function TermsPage() {
    const { t } = useLanguage();
    return (
        <main className="min-h-screen bg-black text-white px-6 py-20 md:py-32">
            <div className="max-w-3xl mx-auto">
                <Link href="/" className="text-white/50 hover:text-white mb-8 block transition-colors">
                    &larr; {t.common.back_to_home}
                </Link>

                <h1 className="text-4xl font-light mb-8">Terms of Service</h1>
                <p className="text-white/50 mb-12">{t.common.last_updated}: February 12, 2026</p>

                <div className="space-y-8 text-white/80 font-light leading-relaxed">
                    <section>
                        <h2 className="text-xl font-medium text-white mb-4">1. Introduction</h2>
                        <p>
                            Welcome to Nano Photography. By accessing or using our website and services, you agree to be bound by these Terms of Service.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-xl font-medium text-white mb-4">2. Use of Service</h2>
                        <p>
                            Nano Photography provides AI-powered image generation services. You may use our services for lawful purposes only. You agree not to upload any illegal, offensive, or infringing content.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-xl font-medium text-white mb-4">3. Credits and Payments</h2>
                        <p>
                            Our services operate on a credit-based system. Credits are purchased in advance and used to generate images. Prices are subject to change without notice. All payments are processed securely through our payment provider, Paddle.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-xl font-medium text-white mb-4">4. Intellectual Property</h2>
                        <p>
                            You retain ownership of the original images you upload. You are granted a commercial license to use the images generated by our AI service for your specific purposes, subject to these terms.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-xl font-medium text-white mb-4">5. Limitation of Liability</h2>
                        <p>
                            Nano Photography is provided "as is" without warranties of any kind. We are not liable for any indirect, incidental, or consequential damages arising from your use of the service.
                        </p>
                    </section>
                </div>
            </div>
        </main>
    );
}
