"use client";

import Link from "next/link";
import { useLanguage } from "@/lib/i18n";

export default function PrivacyPage() {
    const { t } = useLanguage();
    return (
        <main className="min-h-screen bg-black text-white px-6 py-20 md:py-32">
            <div className="max-w-3xl mx-auto">
                <Link href="/" className="text-white/50 hover:text-white mb-8 block transition-colors">
                    &larr; {t.common.back_to_home}
                </Link>

                <h1 className="text-4xl font-light mb-8">Privacy Policy</h1>
                <p className="text-white/50 mb-12">{t.common.last_updated}: February 12, 2026</p>

                <div className="space-y-8 text-white/80 font-light leading-relaxed">
                    <section>
                        <h2 className="text-xl font-medium text-white mb-4">1. Information We Collect</h2>
                        <p>
                            We collect information you provide directly to us, such as your email address when you sign in via Google. We also collect the images you upload for processing and the images generated by our AI.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-xl font-medium text-white mb-4">2. How We Use Your Information</h2>
                        <p>
                            We use your information to provide, maintain, and improve our services. specifically:
                        </p>
                        <ul className="list-disc pl-5 mt-2 space-y-1">
                            <li>To provide the AI image generation service properly.</li>
                            <li>To process your payments and manage your credit balance.</li>
                            <li>To communicate with you about your account and service updates.</li>
                        </ul>
                    </section>

                    <section>
                        <h2 className="text-xl font-medium text-white mb-4">3. Data Storage and Security</h2>
                        <p>
                            Your images and data are stored securely on Google Cloud Platform and Firebase. We implement reasonable security measures to protect your personal information.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-xl font-medium text-white mb-4">4. Third-Party Services</h2>
                        <p>
                            We use third-party services like Paddle for payment processing and Google Firebase for authentication. These parties have their own privacy policies governing the use of your data.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-xl font-medium text-white mb-4">5. Contact Us</h2>
                        <p>
                            If you have any questions about this Privacy Policy, please contact us at support@nano-photography.com.
                        </p>
                    </section>
                </div>
            </div>
        </main>
    );
}
